apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: udagram-api-feed 
  template:
    metadata:
      labels:
        service: udagram-api-feed 
    spec:
      containers:
      - name: udagram-api-feed 
        image: bxhu/udagram-api-feed:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"    
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: POSTGRESS_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: NODE_OPTIONS
          value: '--max-old-space-size=8192'
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
      imagePullSecrets:
      - name: regcred
