apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-user 
  name: udagram-api-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: udagram-api-user 